"""init

Revision ID: c668fc8fc00d
Revises: 
Create Date: 2025-08-22 15:31:36.317529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c668fc8fc00d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archetypes',
    sa.Column('archetype_id', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('building_type', sa.String(), nullable=True),
    sa.Column('construction_period_start', sa.Integer(), nullable=True),
    sa.Column('construction_period_end', sa.Integer(), nullable=True),
    sa.Column('main_material', sa.String(), nullable=True),
    sa.Column('ref_bgf', sa.Float(), nullable=True),
    sa.Column('ref_volume', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('archetype_id')
    )
    op.create_index(op.f('ix_archetypes_archetype_id'), 'archetypes', ['archetype_id'], unique=False)
    op.create_table('components',
    sa.Column('component_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('component_id')
    )
    op.create_index(op.f('ix_components_component_id'), 'components', ['component_id'], unique=False)
    op.create_table('element_types',
    sa.Column('element_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('element_type_id')
    )
    op.create_index(op.f('ix_element_types_name'), 'element_types', ['name'], unique=True)
    op.create_table('products',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('designation_en', sa.String(), nullable=True),
    sa.Column('category_en', sa.String(), nullable=True),
    sa.Column('raw_density', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=False)
    op.create_table('archetype_elements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('archetype_id', sa.String(), nullable=True),
    sa.Column('element_type_id', sa.Integer(), nullable=True),
    sa.Column('ref_area', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['archetype_id'], ['archetypes.archetype_id'], ),
    sa.ForeignKeyConstraint(['element_type_id'], ['element_types.element_type_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('component_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('component_id', sa.String(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('schichtstaerke', sa.Float(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.component_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_component_products_component_id'), 'component_products', ['component_id'], unique=False)
    op.create_index(op.f('ix_component_products_id'), 'component_products', ['id'], unique=False)
    op.create_index(op.f('ix_component_products_product_id'), 'component_products', ['product_id'], unique=False)
    op.create_table('element_components',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=True),
    sa.Column('component_id', sa.String(), nullable=True),
    sa.Column('refurbishment_level', sa.String(), server_default='as-built', nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.component_id'], ),
    sa.ForeignKeyConstraint(['element_id'], ['archetype_elements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_element_components_component_id'), 'element_components', ['component_id'], unique=False)
    op.create_index(op.f('ix_element_components_id'), 'element_components', ['id'], unique=False)
    op.create_index(op.f('ix_element_components_refurbishment_level'), 'element_components', ['refurbishment_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_element_components_refurbishment_level'), table_name='element_components')
    op.drop_index(op.f('ix_element_components_id'), table_name='element_components')
    op.drop_index(op.f('ix_element_components_component_id'), table_name='element_components')
    op.drop_table('element_components')
    op.drop_index(op.f('ix_component_products_product_id'), table_name='component_products')
    op.drop_index(op.f('ix_component_products_id'), table_name='component_products')
    op.drop_index(op.f('ix_component_products_component_id'), table_name='component_products')
    op.drop_table('component_products')
    op.drop_table('archetype_elements')
    op.drop_index(op.f('ix_products_product_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_element_types_name'), table_name='element_types')
    op.drop_table('element_types')
    op.drop_index(op.f('ix_components_component_id'), table_name='components')
    op.drop_table('components')
    op.drop_index(op.f('ix_archetypes_archetype_id'), table_name='archetypes')
    op.drop_table('archetypes')
    # ### end Alembic commands ###
